version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Mongey/terraform-provider-kafka
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: go build
      - store_artifacts:
          path: /go/src/github.com/Mongey/terraform-provider-kafka/terraform-provider-kafka
          destination: terraform-provider-kafka
